### ISSUE TITLE
Svuotamento cache elimina directory css e js

### ISSUE THREAD

**Issue by abidibo** [otto-torino/gino#14]
Svuotando la cache da interfaccia amministrativa (Impostazioni) vengono eliminati tutti i file e directory all'interno della cartella cache. In particolare anche le directory __css__ e __js__ che devono contenere (in debug FALSE) i file minificati. Il problema è che in produzione se mancano queste cartelle i minificati non vengono creati perché mancano le cartelle.

Soluzioni:
1 - non eliminare quelle cartelle
2 - modificare Compressor di modo che crei le directory che gli servono se non presenti

**Comment by guidottim** [comment]
Si è scelta la soluzione di non eliminare le directory css e js
